In [1]:
# Read the data from Github

import pandas as pd
url =  "https://raw.githubusercontent.com/lDabboucy/AAI614_Dabboucy/main/Week%203/niaaa-report2009.csv"

df = pd.read_csv(url)
df.head()

        State  Beer  Wine  Spirits
0     Alabama  1.20  0.22     0.58
1      Alaska  1.31  0.54     1.16
2     Arizona  1.19  0.38     0.74
3    Arkansas  1.07  0.17     0.60
4  California  1.05  0.55     0.73

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   State    51 non-null     object
 1   Beer     51 non-null     float64
 2   Wine     51 non-null     float64
 3   Spirits  51 non-null     float64
dtypes: float64(3), object(1)
memory usage: 1.7+ KB

In [9]:
for column in df.select_dtypes(include="number"):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR
    
    print(f"{column}: Q1 = {Q1:.3f}, Q3 = {Q3:.3f}, IQR = {IQR:.3f}, Lower = {lower_limit:.4f}, Upper = {upper_limit:.4f}")
    outliers = df [
        (df[column] < lower_limit) | (df[column] > upper_limit)
        ]
    if outliers.empty:
        print("No Outliers")
    else:
        display(outliers[["State", column]])
    print()

Beer: Q1 = 1.095, Q3 = 1.365, IQR = 0.270, Lower = 0.6900, Upper = 1.7700
No Outliers

Wine: Q1 = 0.225, Q3 = 0.520, IQR = 0.295, Lower = -0.2175, Upper = 0.9625

                  State  Wine
8  District of Columbia   1.0

Spirits: Q1 = 0.660, Q3 = 0.880, IQR = 0.220, Lower = 0.3300, Upper = 1.2100

                   State  Spirits
7               Delaware     1.25
8   District of Columbia     1.64
29         New Hampshire     1.82